CREATE TABLE IF NOT EXISTS "test-table" (
	"id" integer PRIMARY KEY GENERATED ALWAYS AS IDENTITY (sequence name "test-table_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1)
);
